apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: node-monitor
  labels:                # Used for identifying and grouping resources
    app: node-monitor
spec:
  selector:             # Matches Pods with the same label        
    matchLabels:
      app: node-monitor
  template:
    metadata:
      labels:
        app: node-monitor
    spec:
      containers:            # The container(s) that each Pod will run
      - name: node-exporter
        image: prom/node-exporter:latest   # standard Prometheus exporter
        ports:
        - containerPort:    9100 # Exposes port 9100 for Prometheus metrics
          name: metrics
        resources:
          limits:
            cpu: "100m"
            memory: "128Mi"
          requests:
            cpu: "50m"
            memory: "64Mi"

